# 异常

## Throwable

`Throwable`类是Java语言中所有错误(`Error`)或异常(`Exception`)的超类。

只有当对象是`Throwable`类或者是其子类之一的实例时，才能通过`Java`虚拟机或者`Java throw`语句抛出。

## Error

`Error` 是 `Throwable` 的子类，用于指示合理的应用程序不应该试图捕获的严重问题。

如果出现了`Error`，那就不在程序员的解决范围之内，所以不在此讨论`Error`。

## Exception

`Exception`异常主要分为两类

* `RuntimeException`(运行时异常)，`RuntimeException`被称为【非受查异常】
* `IOException`(输入输出时异常)，`IOException`及其子类异常又被称为【受查异常】

**受查异常：编译器在编译期间要求必须得到处理的那些异常，必须在编译时处理**

## 自定义异常

**注意：**

* 所有异常都必须是 `Throwable` 的子类。
* 如果希望写一个检查性异常类(如果我们希望他的子类必须处理这个异常)，则需要继承 `Exception` 类。
* 如果你想写一个运行时异常类，那么需要继承 `RuntimeException` 类。

```Java
public class TestMain{
    public static void main(String[] args) throws Exception {
        test();
    }

    public static void test() throws Exception{
        if (true){
            throw new MyException(){};
        }
    }
}

class MyException extends Exception{
    public MyException() {
        super();
    }
}
```

## 异常的处理

### 通过`try...catch`语句块来处理

```Java
public class TestMain {
    public static void main(String[] args) {
        try {
            test();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void test() throws Exception {
        if (true) {
            throw new MyException() {
            };
        }
    }
}

class MyException extends Exception {
    public MyException() {
        super();
    }
}

```

### throws抛出

```Java
package com.study.test;

public class TestMain{
    public static void main(String[] args) throws Exception {
        test();
    }

    public static void test() throws Exception{
        if (true){
            throw new MyException(){};
        }
    }
}

class MyException extends Exception{
    public MyException() {
        super();
    }
}
```

### finally关键字

一般来说，如果程序发生了异常，错误代码后面的代码都不会再执行，但是有时我们却希望程序就算出现了异常，也必须完成一些事情，那我们将这部分必须完成的语句放在`finally`代码块中，因为无论是否发生异常，`finally`代码块中的代码总会被执行。

```Java
try{
  // 程序代码
}catch(异常类型1 异常的变量名1){
  // 程序代码
}catch(异常类型2 异常的变量名2){
  // 程序代码
}finally{
  // 程序代码
}
```
